#!/bin/bash

REPO_URL=$1

BASE_DIR="$REPO_FOLDER"
mkdir -p "$BASE_DIR"
cd "$BASE_DIR"

REPO_DIR=$(basename "$REPO_URL" .git)

if [ -d "$REPO_DIR" ]; then
    echo "Removing existing directory: $REPO_DIR"
    rm -rf "$REPO_DIR"
fi

git clone --recurse-submodules "$REPO_URL" || { echo "ERROR: Failed to clone $REPO_URL"; exit 1; }

BUILD_DIR="$BASE_DIR/$REPO_DIR/build"
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

# Try to configure with cmake - may fail due to missing dependencies
cmake -S .. -B . -DCMAKE_CXX_STANDARD=17 -DCMAKE_C_STANDARD=99 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON || echo "CMake configure failed, checking for compile_commands.json anyway..."

# Check if compile_commands.json was generated
if [ ! -f "compile_commands.json" ]; then
    echo "ERROR: compile_commands.json was not generated by CMake"
    exit 1
fi

echo "compile_commands.json found, proceeding..."

# Build is optional - CFG generation only needs compile_commands.json
cmake --build . || echo "Build failed, but compile_commands.json exists"